### ISSUE TITLE
luajit-msgpack-pure.lua:433: unimplemented

### ISSUE THREAD

**Issue by poembro** [catwell/luajit-msgpack-pure#13]
`
2018/03/02` 19:13:45 [error] 31794#0: *287 lua entry thread aborted: runtime error: /data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: unimplemented
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: in function 'dynamic'
	/data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:567: in function 'unpack'
	/data/web/openresty-websocket/libs/pushs.lua:77: in function 'unpack'
	/data/web/openresty-websocket/websocket.lua:180: in function 'run'
	content_by_lua(nginx.conf:106):3: in function <content_by_lua(nginx.conf:106):1>, client: 116.115.11.21, server: ngx.p.qc.com, request: "GET /?order=ccf8f35a2bff&user=2d7zsk&ver=372&reconnect=1&ingame=0 HTTP/1.1", host: "api2.qc.com:4396"
`

nginx_error. log a lot of errors. What should I do?

**Comment by catwell** [comment]
This means there is something in the MessagePack you are trying to unpack which is not valid as of the spec the library implements.

Can you share the data that was being unpacked?

**Comment by poembro** [comment]
`

2018/03/02 19:14:33 [error] 31795#0: *445 [lua] websocket.lua:182: run(): -----The original data--------------> 300d9201b3433a5c57494e444f57535c73797374656d33329201b3433a5c57494e444f57535c737973776f7736349200aa433a5c57494e444f57539202be433a5c55736572735c53756761725c417070446174615c526f616d696e679202ae433a5c50726f6772616d446174619202bc433a5c55736572735c53756761725c417070446174615c4c6f63616c9203b6433a5c55736572735c53756761725c4465736b746f709203b7433a5c55736572735c5075626c69635c4465736b746f709204b0433a5c50726f6772616d2046696c65739205b6433a5c50726f6772616d2046696c6573202878383629<--------------, client: 116.205.11.26, server: ngx.p.xubei.com, request: "GET /?order=ccf8f35a2bff&user=2d7zsk&ver=372&reconnect=1&ingame=0 HTTP/1.1", host: "api2.xubei.com:4396"
2018/03/02 19:14:33 [error] 31795#0: *445 lua entry thread aborted: runtime error: /data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: unimplemented
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: in function 'dynamic'
	/data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:567: in function 'unpack'
	/data/web/openresty-websocket/libs/pushs.lua:77: in function 'unpack'
	/data/web/openresty-websocket/websocket.lua:180: in function 'run'
	content_by_lua(nginx.conf:106):3: in function <content_by_lua(nginx.conf:106):1>, client: 116.205.11.26, server: ngx.p.qc.com, request: "GET /?order=ccf8f35a2bff&user=2d7zsk&ver=372&reconnect=1&ingame=0 HTTP/1.1", host: "api2.qc.com:4396"


`

**Comment by catwell** [comment]
Well, I can't reproduce the issue. Either this is not the data you unpack or you don't use the current version of the library.

Script I used:

```lua
local pretty = require "pl.pretty"
local mp = require "luajit-msgpack-pure"

local _byte_from_hex = function(x) return string.char(tonumber(x, 16)) end
local from_hex = function(s) return (s:gsub("(..)", _byte_from_hex)) end

local data = from_hex("300d9201b3433a5c57494e444f57535c73797374656d33329201b3433a5c57494e444f57535c737973776f7736349200aa433a5c57494e444f57539202be433a5c55736572735c53756761725c417070446174615c526f616d696e679202ae433a5c50726f6772616d446174619202bc433a5c55736572735c53756761725c417070446174615c4c6f63616c9203b6433a5c55736572735c53756761725c4465736b746f709203b7433a5c55736572735c5075626c69635c4465736b746f709204b0433a5c50726f6772616d2046696c65739205b6433a5c50726f6772616d2046696c6573202878383629")

local offset, res = 0

while true do
    offset, res =  mp.unpack(data, offset)
    if not offset then break end
    if type(res) == "table" then
        print(offset, type(res), pretty.write(res, ""))
    else
        print(offset, type(res), res)
    end
end
```

Result:

```
1	number	48
2	number	13
24	table	{1,"C:\\WINDOWS\\system32"}
46	table	{1,"C:\\WINDOWS\\syswow64"}
59	table	{0,"C:\\WINDOWS"}
92	table	{2,"C:\\Users\\Sugar\\AppData\\Roaming"}
109	table	{2,"C:\\ProgramData"}
140	table	{2,"C:\\Users\\Sugar\\AppData\\Local"}
165	table	{3,"C:\\Users\\Sugar\\Desktop"}
191	table	{3,"C:\\Users\\Public\\Desktop"}
210	table	{4,"C:\\Program Files"}
235	table	{5,"C:\\Program Files (x86)"}
```

**Comment by poembro** [comment]
sorry !   Please look at this

```
local cjson = require "cjson"
local mp = require "resty.luajit-msgpack-pure"

local _byte_from_hex = function(x) 
        return string.char(tonumber(x, 16)) 
    end
    
local from_hex = function(s) 
        return (s:gsub("(..)", _byte_from_hex)) 
    end

local data = from_hex("1401000100c501001f8b080000000000000bad7cd9aee34a775e8617391ef3ff96bbc57970722e8a9344cd244549543672c099144771102505017219f8c6807de500417299070860c38eede7f8ef63c3798b94b4bb45758b5b7bb7e3ee0634552f56adfad6b7865ae49ffd8bdffc2130a562ee70c10441667a534d3075784e4003745f04dffdf9f937ff81ffa3974591f98599fc2485b15bbeacc3d4c99a12e479f9320ded222b33affaac45a7dc85dffd82629f5106a13f6314f119f9e54811bffc129d3d667ff470e6ec93f6cb75e4302babcfeed1fdb3cb7c5c7e42474238c3855ea32da7f11ae845368533ea98cfef4a7ff4d244ee4b55d469f4e2b849f66285e9e52bae80b306c3cd6bf7cd29dd")

local offset, res = 0

while true do
    offset, res =  mp.unpack(data, offset)
    if not offset then break end
    if type(res) == "table" then
        print(offset, type(res), cjson.encode(res))
    else
        print(offset, type(res), res)
    end
end
```

Result:
```
2017/12/25 23:59:05 [notice] 94247#0: *12 [lua] test.lua:22: 1number20, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"
2017/12/25 23:59:05 [notice] 94247#0: *12 [lua] test.lua:22: 2number1, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"
2017/12/25 23:59:05 [notice] 94247#0: *12 [lua] test.lua:22: 3number0, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"
2017/12/25 23:59:05 [notice] 94247#0: *12 [lua] test.lua:22: 4number1, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"
2017/12/25 23:59:05 [notice] 94247#0: *12 [lua] test.lua:22: 5number0, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"
2017/12/25 23:59:05 [error] 94247#0: *12 lua entry thread aborted: runtime error: /data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: unimplemented
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:433: in function 'dynamic'
        /data/web/openresty-websocket/resty/luajit-msgpack-pure.lua:567: in function 'unpack'
        /data/web/openresty-websocket/test.lua:17: in function </data/web/openresty-websocket/test.lua:1>, client: 192.168.2.1, server: m.ci.cn, request: "GET /test HTTP/1.1", host: "m.ci.cn"

```

**Comment by catwell** [comment]
OK, I understand the issue.

You data appears to be MessagePack v5, whereas this library implements MessagePack v4 with extensions for compatibility with msgpack-js (see #12).

The data type that fails starts with `c5` i.e. it is a `bin16` which does not exist in v4.

The problem is I can't easily implement both the v5 spec and the msgpack-js extensions because they are incompatible.

May I ask:

- Where does your data come from (which library encoded it)?
- Why do you use this library (luajit-msgpack-pure) and not [lua-MessagePack](https://github.com/fperrad/lua-MessagePack)?
- Do you also use this library (luajit-msgpack-pure) to encode MessagePack?

**Comment by poembro** [comment]
sorry！Waiting so long

- I'm using openresty because it supports luajit.
https://github.com/openresty

- I found a library to solve it.
https://github.com/chronolaw/lua-resty-msgpack

**Comment by catwell** [comment]
Yes this is a good choice, just a wrapper around the one I recommended.

**Comment by catwell** [comment]
I have [added a warning](https://github.com/catwell/luajit-msgpack-pure/commit/344614ade7360626c55e53d74ea15eee9d1e424f) about this in the README.
